### ISSUE TITLE
NullPointerException in TracingConsumer

### ISSUE THREAD

**Issue by rahja** [opentracing-contrib/java-rabbitmq-client#2]
Receiving NullPointer exception in consumer, when headers are null. This may happen when message is being sent from Producers who are not using headers or opentracing rmq client.

================================
2018-05-02 14:40:58 ERROR ForgivingExceptionHandler:119 - Consumer io.opentracing.contrib.rabbitmq.TracingConsumer@74c62dfb (amq.ctag-7GgIK06zrLFkQLDACUWgRg) method handleDelivery for channel AMQChannel(amqp://play1@172.23.125.52:5672/,1) threw an exception for channel AMQChannel(amqp://play1@172.23.125.52:5672/,1)
java.lang.NullPointerException
	at io.opentracing.contrib.rabbitmq.HeadersMapExtractAdapter.<init>(HeadersMapExtractAdapter.java:27)
	at io.opentracing.contrib.rabbitmq.TracingUtils.extract(TracingUtils.java:29)
	at io.opentracing.contrib.rabbitmq.TracingUtils.buildChildSpan(TracingUtils.java:49)
	at io.opentracing.contrib.rabbitmq.TracingConsumer.handleDelivery(TracingConsumer.java:65)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by malafeev** [comment]
fixed
